#!/usr/bin/env python

import os.path
current_dir = os.path.dirname(os.path.abspath(__file__))
import sys
import subprocess

python_program = "python2"
try:
    with open("/dev/null","w") as sink:
        subprocess.check_call(["which", python_program], stdout = sink)
except subprocess.CalledProcessError:
    python_program = "python"

print
print "You might want to clear your browsing history if you've recently switched Annotald branches!"
print
s = raw_input("Press ENTER to continue. ")
print

os.system(python_program + " " + current_dir +
          "/treedrawing/treedrawing.py " + ' '.join(sys.argv[1:]))
