= Annotald

Annotald is a program for annotating parsed corpora in the Penn Treebank
format.  For more information on the format (as instantiated by the Penn
Parsed Corpora of Historical English), see
http://www.ling.upenn.edu/hist-corpora/annotation/intro.htm#parsed_files[the
documentation by Beatrice Santorini].  Annotald was originally written
by http://linguist.is/[Anton Ingason] as part of the
http://linguist.is/icelandic_treebank/Icelandic_Parsed_Historical_Corpus_(IcePaHC)[Icelandic
Parsed Historical Corpus] project.  It is currently being developed by
him along with link:$$http://www.ling.upenn.edu/~janabeck/$$[Jana Beck] and
link:$$http://www.ling.upenn.edu/~ecay/$$[Aaron Ecay].

== Obtaining Annotald

The central location for Annotald development is
https://github.com/Annotald/annotald[on Github].  You can view or
download the program's source code from there.  The latest release is
available as a link:#[Python package].  Download the file and install it
with the command `pip install Annotald-x.y.z.tar.gz`.  (Further
information about installation is available iun the user’s manual.)

== Using Annotald

The link:http://annotald/github.com/user.html[Annotald user’s manual]
can be found online.  For developers, there is also
link:http://annotald.github.com/api-doc/global.html[automatically
generated API documentation].
// TODO: link to dev doc instead?

== License

Annotald is available under the terms of the GNU General Public License
(GPL) version 3 or (at your option) any later version.  Please see the
`LICENSE` file included with the source code for more information.

== Funding Sources

Annotald development has been funded by the following funding sources:

- Icelandic Research Fund (RANNÍS), grant #090662011: “Viable Language
  Technology beyond English – Icelandic as a Test Case”
- The research funds of http://www.ling.upenn.edu/~kroch/[Anthony Kroch]
  at the University of Pennsylvania.
