= Developer’s manual for Annotald
Aaron Ecay <ecay@babel.ling.upenn.edu>

== Introduction

This manual documents how to work on developing Annotald

== Prerequisites

In addition to installing the prerequisites for Annotald itself, you
should install the following software packages:

- For running unit tests: the python packages
  http://pypi.python.org/pypi/nose/[nose] and http://pypi.python.org/pypi/coverage[coverage].
- For generating documentation,
  http://www.methods.co.nz/asciidoc/[asciidoc].

You should install the python packages in your system’s Python 2.x tree,
not the Python 3.x tree.  Additionally, this project assumes that the
Python 2 versions of python programs (`python2`, `nosetests2` and
`coverage2`) are accessible with a “ `2` ” appended to explicitly indicate
that they are the Python 2.x versions of these programs.  If your system
is not configured in this way, you will need to arrange for the proper
symlinks to be placed in your `$PATH` (or edit the Makefile).

== Version control

Annotald is developed via git.  It is available from
https://github.com/janabeck/Annotald[github].

// TODO: how to report issues

// TODO: what the git branch layout is

== Documentation

To generate API documentation for the Javascript portion of Annotald,
run one of the following commands, from the root directory of the
Annotald source tree:

- to generate public API docs: `make api-doc`
- to generate all API docs (including private APIs): `make priv-doc`
- to generate the HTML versions of the user’s and developer’s manual:
  `make doc`
- to generate all of the above: `make all-docs`

The output of these documentation-generating processes will be placed in
a folder with a name corresponding to the name of the make target
(public API docs in `api-doc`, etc.)

NOTE: Generating the API documentation currently requires various
customized software packages.  If you’d like to receive these, contact
Aaron Ecay.

== Code Style

Please use the
https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml[Google
Javascript style guide] for Javascript code, except:

- Use 4-space indents, instead of 2-space

Please adhere to the http://www.python.org/dev/peps/pep-0008/[PEP 8]
Python style guide for Python code, except:

- For constistency with Javscript code (which forms the bulk of
  Annotald’s code), camelCase names are permitted.

Generally speaking:

- Avoid trailing whitespace in code
- Avoid lines longer than 80 characters

== Running Annotald

The `bin/annotald-dev` script is provided to run the development version
of Annotald, without needing to install it as a Python package first.

== Architecture

Annotald is divided into two components.  A server, written in Python,
is responsible for reading treebank files into memory, transforming
their hierarchical structure into HTML, and feeding the resultant HTML
(along with Javascript and CSS) to the Chromium browser.  Javascript
code executed in the browser provides the UI of the program, allowing
edits to the structure to be made.  The Javascript communicates back to
the server for tasks requiring access to the filesystem, such as saving
the edited file or validating it with an external program.

=== Python architecture

TODO: maybe write some things about how the python source is laid out

=== Javascript architecture

The javascript code is split into three files, found in the
`treedrawing/data/scripts` subdirectory:

- `treedrawing.contextMenu.js` which contains code for the context
  (right-click) menu
- `treedrawing.utils.js` which contains utility functions
- `treedrawing.js` which contains the main UI code

This is in addition to various third-party libraries distributed with
Annotald, currently:

- http://jquery.com/[jQuery] (along with context-menu and mousewheel plugins)
- http://underscorejs.org/[Underscore]

The functions from this library are available to Annotald JS code at all
times.

The JS files have a table of contents, which is generated from comments
in the source code.  A heading in the table of contents is indicated by
a comment beginning with the characters `//`, followed by a number of
equals signs equal to five times the heading level in the TOC (5 equals
signs for a first-level heading, 10 for a second-level heading, etc.),
followed by the text of the TOC heading.  The TOC is generated by the
Emacs lisp functions in `annotald-dev.el`.

==== Undo/redo

The undo and redo system in Annotald functions by storing references to
the root (top-level) tree(s) that are affected by an editing operation.  There
are three functions that inform the undo system of changes to take
place.  Calling `stackTree` notifies the system that a change will take
place in the root tree to which the function’s argument belongs.
`registerNewRootTree` and `registerDeletedRootTree` inform the system of
changes in the number of root trees in the file.  See the APi docs fo
these functions for more information.

All functions in the Annotald core are undo-aware, thus if your code
modifies the contents of the file through these functions it does not
need to beother with undo.  If you write new code that manipulates the
DOM directly (or through jQuery), you must make sure that your code is
undo-aware.

Aaron Ecay is the author of the undo system, and can help you interface
your code with it.

== Testing

// TODO: link to overview of TDD?

Running unit tests for the Python code is accomplished by running the
command `make test`.  This also automatically generates a test coverage
report, which can be viewed by opening the file `htmlcov/index.html` in
a browser.

Javascript tests are run by navigating to `localhost:8080/test` with
Annotald running, and clicking the “Run Tests” button.

Generally speaking, new code contributed to Annotald should be
accompanied by appropriate tests.
